### ISSUE TITLE
[NEW FUNCTION] MemoServ style message system

### ISSUE THREAD

**Issue by RhinosF1** [quirc-bot/QuIRC#16]
**Feature Name**
Message System
**What will it do?**
Queue a message and deliver to first person matching ident/nick/cloak to join.
**Suggested Stalkwords**
PM only
**Who can use it?**
Everyone to Everyone
**Does it need access to other APIs**
No
**Have you discussed it with the team?**
[Yes]

See #12 and #10

**Comment by sario528** [comment]
Closing as out of scope
