### ISSUE TITLE
[BUG] - loop on greetings bot in if parrotbot exists or similar function on second bot

### ISSUE THREAD

**Issue by muerdogan** [quirc-bot/QuIRC#27]
**Describe the bug**
Bot will get stuck in loop on greetingsbot when the greetingsbot is used on another bot or parrot bot is in the channel
**To Reproduce**
Bring two bots with greetingsbot enabled
trigger greetingsbot
watch them get stuck in a loop

**Expected behavior**
Will not respond to same user more than once
**Log**
[##test1] @ 2019-05-26 23:15:41 - b1ack0p : hi buttbot_
 [##test1] @ 2019-05-26 23:15:41 -RF1_Bot : Hello there b1ack0p!
 [##test1] @ 2019-05-26 23:15:41 - buttbot_ : Hey b1ack0p!
 [##test1] @ 2019-05-26 23:15:41 - buttbot_ : Hello RF1_Bot!
 [##test1] @ 2019-05-26 23:15:41 -RF1_Bot : Hi buttbot_!
 [##test1] @ 2019-05-26 23:15:42 - buttbot_ : Hi there RF1_Bot!
 [##test1] @ 2019-05-26 23:15:42 -RF1_Bot : Hi there buttbot_!
 [##test1] @ 2019-05-26 23:15:42 - buttbot_ : Hello RF1_Bot!
 [##test1] @ 2019-05-26 23:15:42 -RF1_Bot : Hi buttbot_!
 [##test1] @ 2019-05-26 23:15:42 - buttbot_ : Hello RF1_Bot!
 [##test1] @ 2019-05-26 23:15:42 -RF1_Bot : Hello buttbot_!
 [##test1] @ 2019-05-26 23:15:43 - buttbot_ : Hello RF1_Bot!
 [##test1] @ 2019-05-26 23:15:43 -RF1_Bot : Hi there buttbot_!
 [##test1] @ 2019-05-26 23:15:43 - buttbot_ : Hi RF1_Bot!
 [##test1] @ 2019-05-26 23:15:43 -RF1_Bot : Hi there buttbot_!
 [##test1] @ 2019-05-26 23:15:43 - buttbot_ : Hello RF1_Bot!
 [##test1] @ 2019-05-26 23:15:43 -RF1_Bot : Hello buttbot_!
 [##test1] @ 2019-05-26 23:15:44 - buttbot_ : Hey RF1_Bot!
 [##test1] @ 2019-05-26 23:15:47 - b1ack0p : wow
 [##test1] @ 2019-05-26 23:15:50 - b1ack0p : looping
 [##test1] @ 2019-05-26 23:16:06 - b1ack0p : hi buttbot_
 [##test1] @ 2019-05-26 23:16:06 -RF1_Bot : Hello there b1ack0p!
 [##test1] @ 2019-05-26 23:16:06 - buttbot_ : Hi b1ack0p!
 [##test1] @ 2019-05-26 23:16:06 -RF1_Bot : Hi there buttbot_!
 [##test1] @ 2019-05-26 23:16:06 - buttbot_ : Hey RF1_Bot!
 [##test1] @ 2019-05-26 23:16:06 - buttbot_ : Hello there RF1_Bot!
 [##test1] @ 2019-05-26 23:16:06 -RF1_Bot : Hello buttbot_!
 [##test1] @ 2019-05-26 23:16:06 -RF1_Bot :  hello there rf1_bot!
 [##test1] @ 2019-05-26 23:16:07 - buttbot_ : Hello there RF1_Bot!
 [##test1] @ 2019-05-26 23:16:07 -RF1_Bot : Hello there buttbot_!
 [##test1] @ 2019-05-26 23:16:07 - buttbot_ : Hi RF1_Bot!
 [##test1] @ 2019-05-26 23:16:07 -RF1_Bot : Hi there buttbot_!
 [##test1] @ 2019-05-26 23:16:07 - buttbot_ : Hello there RF1_Bot!
 [##test1] @ 2019-05-26 23:16:07 -RF1_Bot : Hi there buttbot_!
 [##test1] @ 2019-05-26 23:16:07 - buttbot_ : Hi there RF1_Bot!
 [##test1] @ 2019-05-26 23:16:07 -RF1_Bot : Hello buttbot_!
 [##test1] @ 2019-05-26 23:16:08 - buttbot_ : Hello there RF1_Bot!
 [##test1] @ 2019-05-26 23:16:08 -RF1_Bot : Hello buttbot_!
 [##test1] @ 2019-05-26 23:16:08 - buttbot_ : Hi RF1_Bot!
 [##test1] @ 2019-05-26 23:16:08 -RF1_Bot : Hey buttbot_!
 [##test1] @ 2019-05-26 23:16:09 - buttbot_ : Hey RF1_Bot!
 [##test1] @ 2019-05-26 23:16:12 - b1ack0p : butt buttbot_

**Comment by RhinosF1** [comment]
Thanks @muerdogan - The best way would be to check who last sent a message that caused greetingsbot to run and not respond if it was the same user.

**Comment by RhinosF1** [comment]
Seems to stop when interrupted by another message but I'm half expecting that

**Comment by RhinosF1** [comment]
Fixed in beta
