### ISSUE TITLE
[FEATURE] UNO game request

### ISSUE THREAD

**Issue by muerdogan** [quirc-bot/QuIRC#28]
is it possible to make a uno script runs in QuIRC Bot? 
a replica model based on original eggdrop .tcl script by Marky'color uno written in Python would be perfect which can be found in this link : 
original: http://www.egghelp.org/tclhtml/3478-4-0-0-1-uno.htm
github: https://github.com/overdrive-irc/eggdrop-color-uno

**Comment by RhinosF1** [comment]
Resubmit via https://github.com/quirc-bot/QuIRC/issues/new?assignees=RhinosF1&labels=enhancement&template=new-function.md&title=%5BNEW+FUNCTION%5D
