### ISSUE TITLE
[FEATURE] seperated scripts

### ISSUE THREAD

**Issue by muerdogan** [quirc-bot/QuIRC#29]
is it possible to load features in seperated files? actual bot can be plain so by users choice scripts/python codes (weather, title, buttbot, games..etc) can be loaded seperately maybe? like eggdrop or perl bots.

**Comment by RhinosF1** [comment]
The whole point of this is once it's built it will be a QUick Interenet Relay Chat bot system.

Developers are more than welcome within the terms of applicable licenses to modify, copy or distribute the code.
