### ISSUE TITLE
[NEW FUNCTION] UNO Game

### ISSUE THREAD

**Issue by muerdogan** [quirc-bot/QuIRC#30]
**Feature Name**
UNO Game
**What will it do?**
UNO Game based on classic Marky's color uno eggdrop .tcl script text based IRC game. Original scripts can be found in below links :
original script by Marky: http://www.egghelp.org/tclhtml/3478-4-0-0-1-uno.htm
github modified edition: https://github.com/overdrive-irc/eggdrop-color-uno

**Suggested Stalkwords**
What ping will trigger it?
**Who can use it?**
Everyone.
**Does it need access to other APIs**
no API needed.
**Have you discussed it with the team?**
Yes

**Comment by RhinosF1** [comment]
Thanks @muerdogan 

@dschultzdev - How much do you think this will affect other functions? Not sure how safe this would be to implement so holding off on approving this.

**Comment by muerdogan** [comment]
this is game manual link explanation of how to play UNO: http://www.noprivilege.com/ab/uno-howto.html

**Comment by RhinosF1** [comment]
@dschultzdev - This was the ticket I was talking about

**Comment by dschultzdev** [comment]
Looks good to me

**Comment by RhinosF1** [comment]
Giving this lowest priority - @dschultzdev - I'm assigning this to you - up to you when to push it but I think it's best it is held off until after at least beta1 goes live

**Comment by muerdogan** [comment]
.tcl script game commands

Marky's Color Uno
Copyright (C) 2004-2008 Mark A. Day (techwhiz@embarqmail.com)

Uno(tm) is Copyright (C) 2001 Mattel, Inc. (official Uno card game license)

This is a simple uno game that I wrote for eggdrop-1.6. It plays much
like other uno bots, responds much faster, makes use of color, has play
shortcuts, and the robot player wins games ;-)

Bot commands:

 !unocmds 	command list
 !remove [nick] remove [nick] (or yourself) from the current game
 !unowon [nick] show score for [nick]
 !unotop10 	top10 scores
 !unotop10 21	top10 blackjack winners
 !unotop3last   last month's Top3
 !unofast 	monthly fastest game record
 !unohigh 	monthly high score record
 !unostats	this months records
 !unorecords 	all-time records
 !uno 		start an uno game
 !stop 		stop uno

 Removing someone other than oneself is limited to channel ops.

Commands during play:

 jo	join an uno game
 od	show current playing order
 ti	show current game running time
 ca	re-display and sort cards in hand 
 pl	play a card
 cd	show current top card
 tu   	show whose turn it is
 dr	draw a card
 co	change color
 pa 	pass to next player
 ct  	show how many cards each player has left
 st	card stats

Examples of card play:

  to play a blue 4 card: pl b4
  to play a red skip card: pl rs
  to play a red reverse card : pl rr
  to play a yellow draw two card: pl yd
  to play wild card : pl w
  to play a wild draw four card: pl wd
  after wild cards played you need to choose color for example blue color: co b

Enjoy,
Marky

**Comment by muerdogan** [comment]
One of the game functions is deleting scores monthly as below automatically : 

Day changed to 01 Jun 2019
00:00:00<+UN0-bot> UNO! Clearing monthly scores

**Comment by muerdogan** [comment]
screenshot of game start : 
https://postimg.cc/MvB0D6wN

screenshot of game end
https://postimg.cc/fthkMNpt

**Comment by RhinosF1** [comment]
Declining this for now as I can't see it going in for a long while  and it's been stale for quite a while
