### ISSUE TITLE
[FEATURE] Improved butt bot

### ISSUE THREAD

**Issue by RhinosF1** [quirc-bot/QuIRC#32]
**Is your feature request related to a problem? Please describe.**
Original butt bot is able to do multiple words in one sentence and only parts of words
Might be good to add a dictionary it could do of phrases and more AI based but not sure how
**Describe the solution you'd like**
Implement a improved learning butt bot that can change multiple words and only parts of words

**Additional context**
See https://github.com/j883376/buttbot and http://code.google.com/p/buttbot/

**Comment by muerdogan** [comment]
appearantly buttbot in QuIRC is responding too much comparing original one. i am not sure if original buttbot has an AI. but QuIRC bot seems responding too often without picking. it looks like an annoying parrot.

**Comment by RhinosF1** [comment]
> appearantly buttbot in QuIRC is responding too much comparing original one. i am not sure if original buttbot has an AI. but QuIRC bot seems responding too often without picking. it looks like an annoying parrot.

The default setting is at 25% chance on trigger - If terminal is still open can you copy the content of it and email quircbot@gmail.com with the terminal output so I can review it

**Comment by muerdogan** [comment]
email sent with buttbot debug output on terminal

**Comment by RhinosF1** [comment]
I think there's a few things we can do but this will miss the next update
