### ISSUE TITLE
tidy up install.py and modifysetup.py

### ISSUE THREAD

**Issue by RhinosF1** [quirc-bot/QuIRC#53]

**Comment by sario528** [comment]
Need to specify using 1 and 0 when activating functions

**Comment by sario528** [comment]
install.py does not allow user to enter ow api key.

**Comment by sario528** [comment]
TODO: add weatherbot units to scripts

**Comment by sario528** [comment]
TODO: add linkbot to scripts

**Comment by sario528** [comment]
install.py

Progress so far: added linkbot, temp units, username and realname defaults and tweaked wording.

Bugs uncovered: can't input ow api key, defaults aren't actually used.

Other changes to be made: allow inputting of quotes in quotes file

**Comment by sario528** [comment]
modifysetup.py

Progress so far:added linkbot, units, realname, and username, fixed some syntax errors

Bugs uncovered: Script doesn't actually work! You can pick a setting, but you can't actually update it.

All bugs listed are going to get their own issues, and I'll merge what I have and close this issue.

**Comment by sario528** [comment]
Merged PR #86
