### ISSUE TITLE
[BUG] in installation script

### ISSUE THREAD

**Issue by sario528** [quirc-bot/QuIRC#63]
Fresh install of ver 1.0.1

Run install.py get following error:
Traceback (most recent call last):
  File "install.py", line 26, in <module>
    nick = raw_input('What is your bot nick? ')
NameError: name 'raw_input' is not defined

**Comment by RhinosF1** [comment]
Are you running in python3?

**Comment by sario528** [comment]
Theoretically, I only have python 3 on my machine, however I tried with the python3 command and received this error:
Traceback (most recent call last):
File "install.py", line 26 in <module>
nick = raw_input('What is your bot nick? ')
NameError: name 'raw_input' is not defined

**Comment by RhinosF1** [comment]
I believe raw_input should be replaced with input for py3 so tagging as part of the python 3 upgrade that I should eventually do

**Comment by RhinosF1** [comment]
Locking for now - will reopen when unstalls

**Comment by sario528** [comment]
Fixed
