### ISSUE TITLE
SQLite Users Database

### ISSUE THREAD

**Issue by examknow** [quirc-bot/QuIRC#71]
**Feature Name**
Users Database
**What will it do?**
There will be a "users.db" file that will hold records of users and their privilleges. For example it will allow channel x to have different chanops than channel y.
**Suggested Stalkwords**
To manage the DB use "!addop channel nick" and "!delop channel nick"
**Who can use it?**
Bot admins can manage the DB
**Does it need access to other APIs**
SQLite3
**Have you discussed it with the team?**
No

**Comment by sario528** [comment]
Fix cherry-picked to Beta-1.1, closing.

**Comment by sario528** [comment]
Closed in error.

**Comment by sario528** [comment]
Closing as rejected, out of scope for the project
